# Generated by Django 5.1.1 on 2024-10-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_first_name', models.CharField(max_length=100)),
                ('user_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user_mail', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=100)),
                ('user_phoneno', models.CharField(blank=True, max_length=15, null=True)),
                ('is_superadmin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
