# Generated by Django 5.1.1 on 2024-10-01 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_areamodel_regionmodel_zonemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodGroupModel',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GenderModel',
            fields=[
                ('gender_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MemberModel',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('admission_no', models.CharField(max_length=100)),
                ('member_name', models.CharField(max_length=100)),
                ('mailid', models.EmailField(max_length=254)),
                ('mobile_no', models.CharField(max_length=50)),
                ('whatsapp_no', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('employment', models.CharField(max_length=100)),
                ('nominee_name', models.CharField(blank=True, max_length=100, null=True)),
                ('nominee_address', models.CharField(blank=True, max_length=100, null=True)),
                ('nominee_dob', models.DateField(blank=True, null=True)),
                ('nominee_mobileno', models.CharField(blank=True, max_length=50, null=True)),
                ('relation_with_member', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('blood_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserApp.bloodgroupmodel')),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserApp.gendermodel')),
            ],
        ),
        migrations.CreateModel(
            name='MemberFamilyModel',
            fields=[
                ('family_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('relation', models.CharField(max_length=100)),
                ('education', models.CharField(blank=True, max_length=100, null=True)),
                ('employment', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserApp.gendermodel')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.membermodel')),
            ],
        ),
        migrations.CreateModel(
            name='UnitModel',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('affliation_number', models.CharField(max_length=50, null=True, unique=True)),
                ('unit_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserApp.areamodel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_admin', to='UserApp.usermodel')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserApp.regionmodel')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserApp.zonemodel')),
            ],
        ),
        migrations.AddField(
            model_name='membermodel',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserApp.unitmodel'),
        ),
        migrations.AddField(
            model_name='membermodel',
            name='user_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserApp.userrole'),
        ),
    ]
