# Generated by Django 5.1.1 on 2024-10-08 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_bloodgroupmodel_gendermodel_userrole_membermodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermodel',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='blood_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserApp.bloodgroupmodel'),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='employment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserApp.gendermodel'),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='mailid',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='whatsapp_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
