# Generated by Django 5.1.1 on 2024-10-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_alter_membermodel_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitmodel',
            name='unit_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
